### ISSUE TITLE
Build Failure (access modifiers)

### ISSUE THREAD

**Issue by lilwhitemouse** [krafs/RimRef#24] opened 2023-01-22 19:27 UTC
I am updating an old mod to 1.4 and ran into this error:
> Error CS0507: 'ITab_RestrictedStorage.FillTab()': cannot change access modifiers when overriding 'protected' inherited member 'InspectTabBase.FillTab()' (CS0507) (RestrictedStorage)

This definitely worked earlier, but now it is expecting `FillTab` to be protected?  Is there something new one has to do?

Thanks

**Comment by pardeike** [comment] 2023-01-22 20:20
No, you should define your override as public

**Comment by krafs** [comment] 2023-01-22 21:12
FillTab is protected, yes. But I'm assuming the mod project is using some kind of publicizer, that maybe somehow broke when you forked the repo? That's the only reason I can think of why this could have worked before, but not now.

Do you have a link to the repo?

**Comment by lilwhitemouse** [comment] 2023-01-23 01:05
https://github.com/lilwhitemouse/RimWorld-RestrictedStorage/tree/5ba1e0e73673cc57c9a972b51d0f2457ef405035

Thanks for taking a look - I am very confused because I thought the only thing I was using was the default krafs?

I have attached link to the previous version - where it worked.  I have updated this project to go ahead and use `protected` because it should work okay, but I have another similar project that I am worried will have the same problem

**Comment by krafs** [comment] 2023-01-23 08:13
The project you linked doesn't compile, so I don't see how it could have worked. The problem is indeed the `FillTab` override. There's even a comment [here ](https://github.com/lilwhitemouse/RimWorld-RestrictedStorage/blob/5ba1e0e73673cc57c9a972b51d0f2457ef405035/Source/ITab_RestrictedStorage.cs#L21) indicating that they're using a publicizer, presumably [Krafs.Publicizer](https://github.com/krafs/Publicizer). However, there's no publicizer referenced or configured anywhere, making me think they either configured it externally on their local computer, or ran a manual publicize-step with some other tool. Hard to say.

Either way, the solution is to change the override-method's access modifier from `public` to `protected`, just like you've done.
This particular project doesn't seem to take advantage of the publicizer anyway, so you could stop there if you'd like.

If you do want to utilize a publicizer, turning all private members of an assembly public so you don't have to use reflection, you can do that too. There are many different libraries that do that.

Here's doing it with Krafs.Publicizer:
Add this to the project's csproj:
```xml
<ItemGroup>
  <PackageReference Include="Krafs.Publicizer" Version="2.2.0" />
</ItemGroup>
```
Then configure the publicizer by adding **one** of the following segments:
```xml
<ItemGroup>
  <Publicize Include="Assembly-CSharp" IncludeVirtualMembers="false" />
</ItemGroup>
```
```xml
<ItemGroup>
  <Publicize Include="Assembly-CSharp" />
  <DoNotPublicize Include="Assembly-CSharp:Verse.InspectTabBase.FillTab" />
</ItemGroup>
```
Since you want to override a non-public method in the project, we want to **not** publicize that specific method, or you risk getting access mismatch errors at runtime. That's what both of the above configurations do, but in different ways.

You can read more about Krafs.Publicizer [here](https://github.com/krafs/Publicizer), and the specific override behaviour [here](https://github.com/krafs/Publicizer#overriding-publicized-members).

**Comment by krafs** [comment] 2023-01-29 13:29
I'll close this issue as resolved. Re-open if you feel like you didn't get the help you needed.

**Closed by krafs** 2023-01-29 13:29 UTC
Labels: question
